
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: freelancer_platform
      NODE_ENV: docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./freelancer-platform-backend
    container_name: backend_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: freelancer_platform
      NODE_ENV: docker

  frontend:
    build: ./freelancer-platform-frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
